name: Upload to PyPI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')

    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.10"
      - name: Install dependencies
          pip install --upgrade pip
          pip install poetry
      - name: Build package
        run: poetry build
      - name: Publish package
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
